services:

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Authentication\Authentication:
  :
    arguments:
    - '@contao.framework'
    - '@contao.security.user_checker'
    - '@session'
    - '@security.token_storage'
    - '@event_dispatcher'
    - '@request_stack'
    - '@monolog.logger.contao'
    public: true


