services:

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Controller\FrontendModule\SwissAlpineClubOidcFrontendLogin:
    arguments:
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Session'
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.frontend_module, category: user }
    - { name: container.service_subscriber }
    public: true


