services:

  # Contao parse backend template hook
  Markocupic\SwissAlpineClubContaoLoginClientBundle\EventListener\Contao\ParseBackendTemplateListener:
    public: true
    arguments:
    - "@request_stack"
    - "@contao.framework"
    tags:
    - { name: kernel.event_listener, event: contao.parseBackendTemplate, method: addLoginButtonToTemplate }
