parameters:
  swiss_alpine_club_contao_login_client.csrf_token_check: false
  swiss_alpine_club_contao_login_client.session.attribute_bag_name: swiss_alpine_club_contao_login_client_attr
  swiss_alpine_club_contao_login_client.session.attribute_bag_key: _swiss_alpine_club_contao_login_client_attr
  swiss_alpine_club_contao_login_client.session.flash_bag_key: _swiss_alpine_club_contao_login_client_flash_bag



