parameters:
  # Override these settings in config/config.yml
  markocupic.swiss_alpine_club_contao_login_client_bundle.client_secret: '*************'
  markocupic.swiss_alpine_club_contao_login_client_bundle.redirect_uri: 'https://sac-pilatus.ch/ssoauth/frontend'
  markocupic.swiss_alpine_club_contao_login_client_bundle.url_authorize: 'https://ids01.sac-cas.ch:443/oauth2/authorize'
  markocupic.swiss_alpine_club_contao_login_client_bundle.url_access_token: 'https://ids01.sac-cas.ch:443/oauth2/token'
  markocupic.swiss_alpine_club_contao_login_client_bundle.resource_owner_details: 'https://ids01.sac-cas.ch:443/oauth2/userinfo'
  markocupic.swiss_alpine_club_contao_login_client_bundle.client_id: '***************'
  markocupic.swiss_alpine_club_contao_login_client_bundle.add_to_member_groups: 'a:1:{i:0;s:1:"9";}'
  markocupic.swiss_alpine_club_contao_login_client_bundle.redirect_uri_frontend: 'https://sac-pilatus.ch/ssoauth/frontend'
  markocupic.swiss_alpine_club_contao_login_client_bundle.redirect_uri_backend: 'https://sac-pilatus.ch/ssoauth/backend'
  markocupic.swiss_alpine_club_contao_login_client_bundle.enable_backend_sso: true
  markocupic.swiss_alpine_club_contao_login_client_bundle.url_logout: 'https://ids01.sac-cas.ch/oidc/logout'
  # Do not change anything below here
  markocupic.swiss_alpine_club_contao_login_client_bundle.enable_csrf_token_check: false
  markocupic.swiss_alpine_club_contao_login_client_bundle.session.attribute_bag_name: swiss_alpine_club_contao_login_client_attr
  markocupic.swiss_alpine_club_contao_login_client_bundle.session.attribute_bag_key: _swiss_alpine_club_contao_login_client_attr
  markocupic.swiss_alpine_club_contao_login_client_bundle.session.flash_bag_key: _swiss_alpine_club_contao_login_client_flash_bag



