services:
    Markocupic\SwissAlpineClubContaoLoginClientBundle\Server\ServerManager:
        public: true
        autowire: true

    Markocupic\SwissAlpineClubContaoLoginClientBundle\User\RemoteUserManager:
        public: true
        autowire: true

    Markocupic\SwissAlpineClubContaoLoginClientBundle\Security\ContaoBackendLogin:
        public: true
        autowire: true
        arguments:
            $contaoUserProvider: '@contao.security.backend_user_provider'
            $authenticationManager: '@security.authentication.manager'
            $tokenStorage: '@security.token_storage'

    Markocupic\SwissAlpineClubContaoLoginClientBundle\User\RemoteContaoOAuth2User:
        public: true
        autowire: true

    Markocupic\SwissAlpineClubContaoLoginClientBundle\Controller\AuthorizationController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']
