services:

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Controller\Authentication\AuthenticationController:
    public: true
    arguments:
      - '@contao.framework'
      - '@request_stack'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\User\RemoteUser'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\User\User'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\InteractiveLogin\InteractiveLogin'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Oidc\Oidc'

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Oidc\Oidc:
    arguments:
      - '@contao.framework'
      - '@request_stack'
      - '@contao.csrf.token_manager'
      - '@contao.routing.scope_matcher'
    calls:
      - [ initializeFramework ]

  Markocupic\SwissAlpineClubContaoLoginClientBundle\InteractiveLogin\InteractiveLogin:
    arguments:
      - '@contao.framework'
      - '@contao.security.user_checker'
      - '@security.token_storage'
      - '@event_dispatcher'
      - '@request_stack'
      - '@monolog.logger.contao'
    calls:
      - [ initializeFramework ]

  Markocupic\SwissAlpineClubContaoLoginClientBundle\User\User:
    arguments:
      - '@contao.framework'
      - '@translator'
      - '@security.encoder_factory'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\ErrorMessageManager'
    calls:
      - [ initializeFramework ]

  Markocupic\SwissAlpineClubContaoLoginClientBundle\User\RemoteUser:
    arguments:
      - '@contao.framework'
      - '@translator'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\ErrorMessageManager'
    calls:
      - [ initializeFramework ]

  Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\ErrorMessageManager:
    arguments:
      - '%contao.pretty_error_screens%'
      - '%sac_oauth2_client.session.flash_bag_key%'
      - '@twig'
      - '@contao.framework'
      - '@request_stack'
      - '@security.helper'
      - '@?logger'

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Attribute\ArrayAttributeBag:
    arguments:
      - '%sac_oauth2_client.session.attribute_bag_key%'
    calls:
      - [ 'setName', [ '%sac_oauth2_client.session.attribute_bag_name%' ] ]
