services:


  Markocupic\SwissAlpineClubContaoLoginClientBundle\Controller\Authorization\AuthorizationController:
    arguments:
    - '@contao.framework'
    - '@session'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\User\RemoteUser'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\User\User'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\InteractiveLogin\InteractiveLogin'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Oidc\Oidc'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Oidc\Oidc:
    arguments:
    - '@contao.framework'
    - '@request_stack'
    - '@session'
    - '@contao.csrf.token_manager'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\InteractiveLogin\InteractiveLogin:
    arguments:
    - '@contao.framework'
    - '@contao.security.user_checker'
    - '@session'
    - '@security.token_storage'
    - '@event_dispatcher'
    - '@request_stack'
    - '@monolog.logger.contao'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\User\User:
    arguments:
    - '@contao.framework'
    - '@session'
    - '@monolog.logger.contao'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\User\RemoteUser:
    arguments:
    - '@contao.framework'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\User\User'
    - '@session'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\PrintErrorMessage:
    arguments:
    - '%contao.pretty_error_screens%'
    - '@twig'
    - '@contao.framework'
    - '@request_stack'
    - '@security.helper'
    - '@?logger'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Attribute\ArrayAttributeBag:
    arguments:
    - '%swiss_alpine_club_contao_login_client_session_attribute_bag_key%'
    calls:
    - ['setName', ['%swiss_alpine_club_contao_login_client_session_attribute_bag_name%']]


