services:

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Controller\Authorization\AuthorizationController:
    arguments:
    - '@contao.framework'
    - '@request_stack'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Session'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\User\RemoteUser'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\User\User'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\InteractiveLogin\InteractiveLogin'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\AppChecker\AppChecker'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Authorization\AuthorizationHelper'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\PrintErrorMessage'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\InteractiveLogin\InteractiveLogin:
    arguments:
    - '@contao.framework'
    - '@contao.security.user_checker'
    - '@session'
    - '@security.token_storage'
    - '@event_dispatcher'
    - '@request_stack'
    - '@monolog.logger.contao'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\User\User:
    arguments:
    - '@contao.framework'
    - '@session'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Session'
    - '@monolog.logger.contao'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\AppChecker\AppChecker:
    arguments:
    - '@contao.framework'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\PrintErrorMessage:
    arguments:
    - '%contao.pretty_error_screens%'
    - '@twig'
    - '@contao.framework'
    - '@request_stack'
    - '@security.helper'
    - '@?logger'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Authorization\AuthorizationHelper:
    arguments:
    - '@contao.framework'
    - '@contao.csrf.token_manager'
    - '@request_stack'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\User\RemoteUser:
    arguments:
    - '@contao.framework'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Authorization\AuthorizationHelper'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\User\User'
    - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Session'
    public: true

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Session:
    arguments:
    - '@session'
    public: true


