services:

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Controller\FrontendModule\SwissAlpineClubOidcFrontendLogin:
    arguments:
      - '@contao.framework'
      - '@security.helper'
      - '@request_stack'
      - '@translator'
    tags:
      - { name: contao.frontend_module, category: user }
      - { name: container.service_subscriber }
    public: true


