services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:

  Markocupic\SwissAlpineClubContaoLoginClientBundle\:
    resource: ../src/
    exclude: [ ../src/{ DependencyInjection,Model,Event,Session,Provider }, ../src/Config/ContaoLogConfig.php, ../src/ErrorMessage/ErrorMessage.php ]

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Controller\GetLogoutEndpointController:
    public: true
    arguments:
      - '%sac_oauth2_client.oidc.auth_provider_endpoint_logout%'

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Initializer:
    arguments:
      - '@contao.framework'
      - '@request_stack'
      - '@contao.csrf.token_manager'

  Markocupic\SwissAlpineClubContaoLoginClientBundle\OpenIdConnect\OpenIdConnect:
    arguments:
      - '@contao.framework'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Initializer'
      - '@request_stack'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Validator\LoginValidator'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\User\ContaoUserFactory'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\InteractiveLogin\InteractiveLogin'
      - '@event_dispatcher'
      - '@monolog.logger.contao'

  Markocupic\SwissAlpineClubContaoLoginClientBundle\InteractiveLogin\InteractiveLogin:
    arguments:
      - '@contao.framework'
      - '@security.token_storage'
      - '@event_dispatcher'
      - '@request_stack'
      - '@monolog.logger.contao'

  Markocupic\SwissAlpineClubContaoLoginClientBundle\User\ContaoUserFactory:
    arguments:
      - '@contao.framework'
      - '@translator'
      - '@security.password_hasher_factory'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Validator\LoginValidator'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\ErrorMessageManager'

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Validator\LoginValidator:
    arguments:
      - '@contao.framework'
      - '@translator'
      - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\ErrorMessageManager'

  Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\ErrorMessageManager:
    arguments:
      - '%sac_oauth2_client.session.flash_bag_key%'
      - '@request_stack'

  Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Attribute\ArrayAttributeBag:
    arguments:
      - '%sac_oauth2_client.session.attribute_bag_key%'
    calls:
      - [ 'setName', [ '%sac_oauth2_client.session.attribute_bag_name%' ] ]
